[lint]
select = [ "ALL" ]
ignore = [
  "ANN001",
  "COM812",
  "D101",
  "D102",
  "D103",
  "D105",
  "D107",
  "EM101",
  "EM102",
  "FIX002",
  "PLR0911",
  "T201",
  "TD002",
  "TD003",
  "TRY003",
]
