# Log level (3=ERR, 6=INFO, 7=DEBUG, 9=VERBOSE)
log_level=6

# CPU freq limit (0=no, other=yes)
limit_cpufreq=1

# NPU freq limit (0=no, other=yes)
limit_npufreq=1

# Fan control (0=no, other=yes)
control_fan=1

