#!/bin/sh
set -e

[ "$1" != 'abort-upgrade' ] || exit 0

version='@krel@'
image_path='@kfile@'

if [ "$1" = 'install' ]; then
    # Create a flag file for postinst
    mkdir -p /usr/lib/modules/$version
    touch /usr/lib/modules/$version/.fresh-install
fi

if [ -d /etc/kernel/preinst.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/preinst.d
fi

exit 0
