#!/bin/sh
set -e

[ "$1" = 'configure' ] || exit 0

version='@krel@'
image_path='@kfile@'

depmod -a -F /boot/System.map-$version $version || true

if [ -d /etc/kernel/postinst.d ]; then
    cat - >/usr/lib/linux/triggers/$version <<EOF
DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	    --arg="$image_path" /etc/kernel/postinst.d
EOF
    dpkg-trigger --no-await linux-update-$version
fi

exit 0
